:sectnums:
:sectnumlevels: 3
:imagesdir: ../images 
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Building Python Containers

There are two several ways in which one can build a container. 

One method that is very easy is to start a container, make changes to the container while it is running, and do a docker commit.  This works, but should you find an error or vulnerability in the base container layers, these are difficult to fix.

tip: Container guilds, such as "docker build" strategies provide an "infrastructure as code" replicable solution

== Dockerfile or Containerfile Use

You may have heard the term "Dockerfile" used as the descriptor of a container build. "Containerfile" is an equivalent term, meaning exactly the same thing. The terminology change comes from a shift of focus from a company name being used, to one of a more generic "open standard" terminology. There are possibly some open source political histories at play. I'll use them interchangeably in order to add to the confusion! In fact, you can name this file anything you want.

=== Building and running a Python Flask Application Container

We can build flask app containers in several ways. They can be simple flask "debug mode" implementations. Production grade Flask, Django, Pyramid, etc.  applications require a WSGI gateway. Gunicorn is currently popular for such applications.

Container builds are commonly done from a file known as a "Dockerfile", or "Containerfile" that describe how containers are built in layers. Layers are added to immutable under layers in order to provide the "diffs" or differential changes to the image. This is patterned after the good old "tar" (Tape ARchive) format from early long term storage formats in the computer industry.

==== Build from a generic image from a "Community Official" image

The following is the "Dockerfile". In this case, we are choosing to call it the "Containerfile.flask".  The `-f`
parameter will ensure that the Docker Build command finds it definition file.

While this is a Flask "hello world", we will not use the default port of 5000. We will use 8080 as that is a good port to use in OpenShift, but you can use whatever you want with a little more effort.


[source,bash]
cat > Dockerfile.hello-world <<UNTILHERE
FROM python:3.9-buster
MAINTAINER YourNameHere imnota@yahoo.com
COPY ./requirements.txt ./helloworld.py .
WORKDIR /
RUN pip install -r requirements.txt
EXPOSE 8080
CMD ["python", "./helloworld.py"]
UNTILHERE

The lines below populate the requirements.txt so that pip can do it's job. IRL (In Real Life) you would probably want to use an on-site or curated pip repository. Of course, you would also care about specifying versions of the installed modules. Today, flask is at 1.1.2.

[source,bash]
cat > requirements.txt <<UNTILHERE
flask==1.1.2
UNTILHERE


The lines below represent the application itself. Put this in a file called helloworld.py


[source,python]
--
cat > helloworld.py <<UNTILHERE
from flask import Flask, request
from flask_restful import Resource, Api

application = Flask(__name__)
api = Api(app)

class Greeting (Resource):
    def get(self):
        return 'Hello World!'

api.add_resource(Greeting, '/') # Route_1

if __name__ == '__main__':
    application.run('0.0.0.0','8080')
UNTILHERE
--

Finally, let's run the command that puts it all together:

[source,bash]
$ podman build -f Containerfile.helloworld -t hello-world


==== UBI: Build from a generic image

Let's start with a build from an "Official Community Dockerhub" base image.

[source, config]
FROM registry.access.redhat.com/ubi8/ubi
RUN yum install -y python3 ; yum clean all
COPY ./requrements.txt /app/requirements.txt
WORKDIR /app
RUN python3 -m pip install -r requirements.txt
COPY ./src /app/src
EXPOSE 8080
ENTRYPOINT ["python3"]
CMD ["src/main.py"]

Here is our slightly different application:

[source,python]
--
from flask import Flask, request
from flask_restful import Resource, Api

application = Flask(__name__)
api = Api(app)

class Greeting (Resource):
    def get(self):
        return 'Hello World!'

api.add_resource(Greeting, '/') # Route_1

if __name__ == '__main__':
    application.run('0.0.0.0','8080')
--
