:sectnums:
:sectnumlevels: 3
:imagesdir: ../images 

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
ifdef::env-github[]
endif::[]

= Building Python Containers

There are two several ways in which one can build a container. 

One method that is very easy is to start a container, make changes to the container while it is running, and do a docker commit.  This works, but should you find an error or vulnerability in the base container layers, these are difficult to fix.

TIP: Container guilds, such as "docker build" strategies provide an "infrastructure as code" replicable solution

== Dockerfile or Containerfile Use

You may have heard the term "Dockerfile" used as the descriptor of a container build. "Containerfile" is an equivalent term, meaning exactly the same thing. The terminology change comes from a shift of focus from a company name being used, to one of a more generic "open standard" terminology. There are possibly some open source political histories at play. I'll use them interchangeably in order to add to the confusion! In fact, you can name this file anything you want.

=== Building and running a Python Flask Application Container

We can build flask app containers in several ways. They can be simple flask "debug mode" implementations. Production grade Flask, Django, Pyramid, etc.  applications require a WSGI gateway. Gunicorn is currently popular for such applications.

Container builds are commonly done from a file known as a "Dockerfile", or "Containerfile" that describe how containers are built in layers. Layers are added to immutable under layers in order to provide the "diffs" or differential changes to the image. This is patterned after the good old "tar" (Tape ARchive) format from early long term storage formats in the computer industry.e.hello-worlld", we will not use the default port of 5000. We will use 8080 as that is a good port to use in OpenShift, but you can use whatever you want with a little more effort.


[source,bash]
cat > Dockerfile.hello-world <<UNTILHERE
FROM python:3.9-buster
MAINTAINER YourNameHere imnota@yahoo.com
COPY ./requirements.txt ./helloworld.py ./
WORKDIR /
RUN pip install -r requirements.txt
EXPOSE 8080
CMD ["python", "./helloworld.py"]
UNTILHERE

So what is happening in the Dockerfile?

FROM represents our source image. We have the repo: ```python```, and the tag ```3.9-buster```

This repo and tag refer to the "Official Community Maintained Container for Python". Will you use that container as a base? Great question. Later podman build -f Dockerfile.copyfiles -t copy-files-into

[source,bash]
cat > requirements.txt <<UNTILHERE
flask==1.1.2
flask_restful==0.3.8
UNTILHERE


The lines below represent the application itself. Put this in a file called helloworld.py


[source,python]
--
cat > helloworld.py <<UNTILHERE
from flask import Flask, request
from flask_restful import Resource, Api

application = Flask(__name__)
api = Api(application)

class Greeting (Resource):
    def get(self):
        return 'Hello World!'

api.add_resource(Greeting, '/') # Route_1

if __name__ == '__main__':
    application.run('0.0.0.0','8080')
UNTILHERE
--


Finally, let's run the command that puts it all together:

[source,bash]
big-test-py

python-38-rhel7

python-data-list

python39

s2i-3.9-fedora

ubi

ubi-httpd

    Documentation Terms Privacy Security About Contact
    All Systems Operational


STEP 1: FROM python:3.9-buster
STEP 2: MAINTAINER YourNameHere imnota@yahoo.com
--> Using cache 7f2392e40e32b4155cf7dd1aeeb951950f0bd44ba53b3daf4789fd051336b750
STEP 3: COPY ./requirements.txt ./helloworld.py .
9b926f09f16ebb4d5037f903aead98e91f19bc6c6e57627a396bb4bec8b2bcd4
STEP 4: WORKDIR /
db42f3cfc1175087e2eac9ae0c57ab275b2481c45b345b06dc9805b58da52de0
STEP 5: RUN pip install -r requirements.txt
Collecting flask==1.1.2
  Downloading Flask-1.1.2-py2.pe.hello-worly3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 357 kB/s 
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 1.9 MB/s 
Collecting MarkupSafe>=0.23
big-test-py

python-38-rhel7

python-data-list

python39

s2i-3.9-fedora

ubi

ubi-httpd

    Documentation Terms Privacy Security About Contact
    All Systems Operational


     |████████████████████████████████| 509 kB 1.7 MB/s 
Collecting six>=1.3.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 1.6 MB/s 
Building wheels for collected packages: MarkupSafe
  Building wheel for MarkupSafe (setup.py) ... done
  Created wheel for MarkupSafe: filename=MarkupSafe-1.1.1-cp39-cp39-linux_x86_64.whl size=32228 sha256=f399be1301220bdd505a0f867fbb171ddc3ed766384ffc7d93a8d75e4f2bb758
  Stored in directory: /root/.cache/pip/wheels/e0/19/6f/6ba857621f50dc08e084312746ed3ebc14211ba30037d5e44e
Successfully built MarkupSafe
Installing collected packages: MarkupSafe, Werkzeug, Jinja2, itsdangerous, click, six, pytz, flask, aniso8601, flask-restful
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 aniso8601-8.1.0 click-7.1.2 flask-1.1.2 flask-restful-0.3.8 itsdangerous-1.1.0 pytz-2020.4 six-1.15.0
dd4484dbee5ded728db01cfae93af44ce837cb75a3fd307a2bb858c97dacc646
STEP 6: EXPOSE 8080
00d26007838a5a54274619f5032421f9f0db2574ebfcf6da26954b28dc9dbe57
STEP 7: CMD ["python", "./helloworld.py"]
STEP 8: COMMIT hello-world-py
1f6870effc8bb9b5a0e609ef42a6f3d97258e9a34b1ad2460a1458bd0b95729c
1f6870effc8bb9b5a0e609ef42a6f3d97258e9a34b1ad2460a1458bd0b95729c

[student@podman ~]$ 
```
[source,bash]
podman images

Yields
```
REPOSITORY                 TAG          IMAGE ID       CREATED        SIZE
localhost/hello-world-py   latest       cc087b7fba56   33 hours ago   919 MB
docker.io/library/python   3.9-buster   a879e610c533   2 days ago     908 MB
[student@podman ~]$ 

```
Very pretty! But will it run??

[source,bash]
podman run --rm -p 8080:8080 localhost/hello-world-py

The --rm will remove the container once it is stopped. The -p maps external host to internal pod ip addresses.
We will be running this container in the foreground, but *not* using -it for interactive terminal.

```
[student@podman ~]$ podman run --rm -p 8080:8080  localhost/hello-world-py 
 * Serving Flask app "helloworld" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
```

curl or browser access port 8080 on your machine to prove out the implementation.

[source,bash]
podman run --rm -it -p 8080:8080  localhost/hello-world-py /bin/bash

Will land you in the container, and apparent root

```
root@f283db2a2d71:/# ls
bin  boot  dev	etc  helloworld.py  home  lib  lib64  media  mnt  opt  proc  requirements.txt  root  run  sbin	srv  sys  tmp  usr  var
root@f283db2a2d71:/# python --version
Python 3.9.1
root@f283db2a2d71:/# which python
/usr/local/bin/python
root@f283db2a2d71:/# 
```

NOTE: my application landed in root, this could be changed by putting it into a 'WORKDIR' working directory in the `Dockerfile.flask` build file


==== UBI: Build from a generic image

[source,bash]
--
mkdir -p src
cat > Dockerfile.ubi <<UNTILHERE
FROM registry.access.redhat.com/ubi8/ubi
RUN yum install -y python3 && yum clean all
COPY ./requirements.txt /application/requirements.txt
WORKDIR /application
RUN python3 -m pip install -r requirements.txt
COPY ./src /application/src
EXPOSE 8080
ENTRYPOINT ["python3"]
CMD ["src/main.py"]
UNTILHERE
--

Here is our requirements file:

[source,python]
--
cat > requirements.txt <<UNTILHERE
flask==1.1.2
flask_restful==0.3.8
UNTILHERE
--


Here is our slightly different application:

[source,python]
--
mkdir src
cat > src/main.py <<UNTILHERE
import sys, oshttps://www.youtube.com/watch?v=eKnqc1L_DFoion)

class Greeting (Resource):
    def get(self):
        return 'Hello World from a generic Universal Base Image optimized for RHEL! try hitting this resource at /python_version'

class PythonVersion (Resource):
    def get(self):
        return (sys.version)


api.add_resource(Greeting, '/')
api.add_resource(PythonVersion, '/python_version')


if __name__ == '__main__':
    application.run('0.0.0.0','8080')
UNTILHERE
--

Let's Build:

[source,bash]
$ podman build -f Dockerfile.ubi -t hello-ubi-py

```
[student@podman ~]$ podman build -f Dockerfile.ubi -t hello-ubi-py
STEP 1: FROM registry.access.redhat.com/ubi8/ubi
STEP 2: RUN yum install -y python3 && yum clean all
--> Using cache 3429af9b9908228c5024f76d0b7cd7e943b0546e4e742a9e9e6cd247ac9fa9e5
STEP 3: COPY ./requirements.txt /app/requirements.txt
--> Using cache a98359d3dad20b182161e26b5ba465e7a22429a3cc5b24e63c659701cfa1cb37
STEP 4: WORKDIR /app
90e1ffd32dc11a6245bce431f418e5b8db041d95aeaac29a7127d27f6d553e32
STEP 5: RUN python3 -m pip install -r requirements.txt
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting flask==1.1.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 2.0MB/s 
Collecting flask_restful==0.3.8 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e9/83/d0d33c971de2d38e54b0037136c8b8d20b9c83d308bc6c220a25162755fd/Flask_RESTful-0.3.8-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1 (from flask==1.1.2->-r requirements.txt (line 1))
  Downloading https://cat Dockerfile.ubiae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 1.7MB/s 
Collecting click>=5.1 (from flask==1.1.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 2.1MB/s 
Collecting itsdangerous>=0.24 (from flask==1.1.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.15 (from flask==1.1.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
    100% |████████████████████████████████| 307kB 1.6MB/s flask==1.1.2
flask_restful==0.3.8
.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/12/f8/ff09af6ff61a3efaad5f61ba5facdf17e7722c4393f7d8a66674d2dbd29f/pytz-2020.4-py2.py3-none-any.whl (509kB)
    100% |████████████████████████████████| 512kB 1.2MB/s 
Collecting aniso8601>=0.82 (from flask_restful==0.3.8->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/93/4e/760c0aaf32034e2da98e1ac6d83b6ffc6d1301132af54c3950ee07785bfa/aniso8601-8.1.0-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 2.3MB/s 
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->flask==1.1.podman build -f Dockerfile.ubi -t hello-ubi-py
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 aniso8601-8.1.0 click-7.1.2 flask-1.1.2 flask-restful-0.3.8 itsdangerous-1.1.0 pytz-2020.4
fb721dc362a5511a024e8a8fe4f98f6b1fd681dbbf6a1df98b2f57c58a47b846
STEP 6: COPY ./src /application/src
e3d5374681e607667bd465fbefaeefb9efd6f4a97b50c8495c86553a50d0917e
STEP 7: EXPOSE 8080
3c485f971916e3aa5e0a7ecf53f9d999077f2344cb77b0d597e96c1dbef6dcee
STEP 8: ENTRYPOINT ["python3"]
978bf1a7e946b9ba8ad5f98c2f192ac7924e485fd233cee7c1227e81991b2776
STEP 9: CMD ["src/main.py"]
STEP 10: COMMIT hello-ubi-py
c9dbc735cff0bd4a36ff8f324884ae14184dd8a106a7601b8ca8f2b4c831e682
c9dbc735cff0bd4a36ff8f324884ae14184dd8a106a7601b8ca8f2b4c831e682
```

Looks good enough to run!

[source,bash]
$ podman run -p 8080:8080 hello-ubi-py

curl or browse to the following endpoints:

[source,bash]
--
$ curl <host>:8080/

$ curl <host>:8080/python_version
--

Ouch, you may have noticed that we got the "RHEL" version of Python, which is a little long in the tooth

We can fix that by using a ubi image made for Python.

=== Red Hat s2i Builder Image

Here is our chance to work with the concept of s2i or sti "source to image"

This installs the s2i executable. Just do the following:

$ sudo subscription-manager repos --enable=rhel-server-rhscl-7-rpms	

$ sudo yum install source-to-image -y

The concept of the source to image is to have a build without a build process. This is an especially powerful concept for those who don't want to build images on their own, and works very well within a kubernetes platform. This is especially favored within OpenShift.

Log into your "git compatible" repository for this next step.  Please fork the repo `sclorg/s2i-python-container`

Clone your fork to your instance, so that we can modify it. 

We will take the last instance of our source code, and requirements.txt and place them into the tree.

```
[student@podman ~]$ git clone https://github.com/jimbarlow/s2i-python-container.git 
Cloning into 's2i-python-container'...
remote: Enumerating objects: 250, done.
remote: Counting objects: 100% (250/250), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 4126 (delta 139), reused 154 (delta 74), pack-reused 3876
Receiving objects: 100% (4126/4126), 1.88 MiB | 1.75 MiB/s, done.
Resolving deltas: 100% (2327/2327), done.
[student@podman ~]$ pwd
/home/student
[student@podman ~]$ ls
Dockerfile.hello-world  Dockerfile.python38  Dockerfile.ubi  helloworld.py  requirements.txt  s2i-python-container  src
[student@podman ~]$ 

```

[source,bash]
$ cp requirements.txt s2i-python-container/examples/setup-test-app/
$ cp src/main.py s2i-python-container/examples/setup-test-app/testapp.py


We now need to commit and push these changes to your repository.  Remember to change 'jimbarlow' into your own account name.

[source,bash]
--
$ cd s2i-python-container
$ git commit -am "replaced sample app"
$ git push

$ sudo s2i build https://github.com/jimbarlow/s2i-python-container.git --context-dir=3.8/test/setup-test-app/ quay.io/jdbarlow/python-38-rhel7:1 python-sample-app
--https://docs.google.com/document/d/1dV4GiazRLXJ7_QOp0yMJjL_yaXsAjeIqzyR1qCdsCQA/editare.

[source,bash]
$ sudo docker run -p 8080:8080 python-sample-app

This outputs:

```
[student@podman ~]$ sudo docker run -p 8080:8080 python-sample-app 
---> Serving application with gunicorn (testapp) ...
[2020-12-11 03:03:54 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-12-11 03:03:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2020-12-11 03:03:54 +0000] [1] [INFO] Using worker: sync
[2020-12-11 03:03:54 +0000] [33] [INFO] Booting worker with pid: 33
[2020-12-11 03:03:54 +0000] [34] [INFO] Booting worker with pid: 34
[2020-12-1/home/jbarlow/workspace/python/python-containers-workshop/Workshop/chapters/building_python_containers.adoc - - [11/Dec/2020:03:04:22 +0000] "GET /python_version HTTP/1.1" 200 82 "-" "curl/7.29.0"
^C[2020-12-11 03:05:05 +0000] [1] [INFO] Handling signal: int
[2020-12-11 03:05:05 +0000] [33] [INFO] Worker exiting (pid: 33)
[2020-12-11 03:05:05 +0000] [34] [INFO] Worker exiting (pid: 34)
[2020-12-11 03:05:05 +0000] [36] [INFO] Worker exiting (pid: 36)
[2020-12-11 03:05:05 +0000] [35] [INFO] Worker exiting (pid: 35)
[2020-12-11 03:05:06 +0000] [1] [INFO] Shutting down: Master
```
NOTE: This /home/jbarlow/workspace/python/python-containers-workshop/Workshop/chapters/building_python_containers.adoc
TIP: The benefit here, is that there is no fussing about with Dockerfiles or any other configuration. Just the requirements.txt and the source tree.

=== Extra Credit Opportunity - Build Your Own Builder Image 

We really want 3.9, right? There is not a completed s2i image based upon RHEL, but one is available on Fedora.

To build this, go into directory `s2i-python/3.9`.  Rename Dockerfile.fedora to Dockerfile.

Then do a `sudo docker build . -t python39`. 

TIP: The reason I suggest using the "." for current directory, is that the very old version of Docker running on RHEL does not allow you to use the -f <filename> to specify the "Dockerfile".

When you do your source to image build, specify this container image at localhost/python39

If you DO NOT want the extra credit, build the app using my image at quay.io/jdbarlow/python39:latest

=== Running the 3.9 Builder Image

Once you build the image (or use mine), create your image with the s2i command as we did with the 3.8 build, your results will be glorious:


```
[student@podman 3.9]$ curl localhost:8080/
"Hello World from a generic Universal Base Image optimized for RHEL! try hitting this resource at /python_version"
[student@podman 3.9]$ curl localhost:8080/python_version
"3.9.0 (default, Oct  6 2020, 00:00:00) \n[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]"
[student@podman 3.9]$ 
```

link:../containers.adoc[Return to workshop top page]

