:sectnums:
:sectnumlevels: 3
:imagesdir: ../images 

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
ifdef::env-github[]
endif::[]

= Persistent Storage on a Server

link:../containers.adoc[Return to workshop top page]

It is time to look at two approaches to getting files access for your containerized Python application.

1) mounting external drives to the container at *run-time*

2) Copying files into the container at *container build time* 

== Mounting Volumes and Security

Mounting data file directories for access by a containerized application is pretty easy. Making sure the security works for the platform is essential.

SELinux extensions for Linux servers have been around for almost 20 years now. Not using them is no longer a viable option in most companies.

It is common to make mount points in the /mnt directory. I'm going to do this in my home directory, however.

This directory will hold data files in the server filesystem, and make no attempt to copy them "into the container"

[source,bash]
$ mkdir datafiles
$ touch data{1..20}.txt
$ touch values{1..30}.csv

This will provide some files to observe within our "app"

Let’s get the SELinux security context correct:

[source,bash]
$ sudo chcon -Rt container_file_t datafiles
$ sudo restorecon ./datafiles

We have modified our application slightly in order to return a list of files as astring that the container may access

[source,bash]
----
cat > testapp.py <<UNTILHERE
import sys
import os
from flask import Flask, request
from flask_restful import Resource, Api

application = Flask(__name__)
api = Api(application)

class Greeting (Resource):
    def get(self):
        return 'Hello Another World from a generic Universal Base Image optimized for RHEL! try hitting this resource at /python_version'

class PythonVersion (Resource):
    def get(self):
        return (sys.version)

class ListFiles (Resource):
    def get(self):
        file_list = os.listdir( '/datafiles' )
        listToStr = ' '.join(map(str, file_list))
        return listToStr

api.add_resource(Greeting, '/')
api.add_resource(PythonVersion, '/python_version')
api.add_resource(ListFiles, '/data_files')

if __name__ == '__main__':
    application.run('0.0.0.0','8080')
UNTILHERE
----

This file should be placed into the following directory:

[source,bash]
$ cp testapp.py s2i-python-container/examples/setup-test-app/testapp.py
$ cd s2i-python-container
$ git commit -am "added file listing in the data volume"
$ git push

Now the container can be re-built 

[source,bash]
$ sudo s2i build https://github.com/jimbarlow/s2i-python-container.git --context-dir=3.9/test/setup-test-app/ quay.io/jdbarlow/python39:latest python-data-list

Now to run this, we will add a new parameter to the docker command line, the -v for volume mounting. This is a colon separated value pair, just as with the ports. This requires a full path of the server directory first, followed by the ":" and the internal directory to mount in the pod.  I added the -d to detach the container from the terminal console.

[source,bash]
$ sudo docker run -d -p 8080:8080 -v /home/student/datafiles:/datafiles python-data-list

Now you can curl the `localhost:8080/data_files` URL to see if you can see the mounted data. These mounts can are read/write by default.

== Copying Data Into the Container Filesystem at Build Time

Here is our second option. At the time we build the container, we can use the COPY command from the "Dockerfile" to copy the files into the overlay file system that the container uses directly.

Let's go back to our first container image for this one for the sake of simplicity

[source,bash]
mkdir -p src
cat > Dockerfile.copyfiles <<UNTILHERE
FROM python:3.9-buster
COPY ./requirements.txt /application/requirements.txt
# Here we will copy in our data directory
COPY ./datafiles /datafiles
# We'll eventualy have to figure out how to get results out
WORKDIR /application
RUN python3 -m pip install -r requirements.txt
COPY ./src /application/src
EXPOSE 8080
ENTRYPOINT ["python3"]
CMD ["src/main.py"]
UNTILHERE

Our application will have to deliver the results outside of the filesystem. Perhaps as a POST someplace?

[source,python]
--
cat > src/main.py <<UNTILHERE
import sys, os
from flask import Flask, request
from flask_restful import Resource, Api

application = Flask(__name__)
api = Api(application)

class Greeting (Resource):
    def get(self):
        return 'Hello World from a generic Universal Base Image optimized for RHEL! try hitting this resource at /python_version'

class PythonVersion (Resource):
    def get(self):
        return (sys.version)

class ListFiles (Resource):
    def get(self):
        return(os.listdir( '/datafiles' ))

api.add_resource(Greeting, '/')
api.add_resource(PythonVersion, '/python_version')
api.add_resource(ListFiles, '/data_files')

if __name.
Total 6 (delta 4), reused 0 (delta 0), pack-reused 0
Just for grins, I thought we would return the list rather than the string in this chapter.

Our requirements.txt stay the same, though we will not use gunicorn here.

Let's build:

[source,bash]
$ podman build -f Dockerfile.copyfiles -t copy-files-into

Let's run:
e.
Total 6 (delta 4), reused 0 (delta 0), pack-reused 0
[source,bash]
$ curl localhost:8080/data_files

Do you see the files returned as a list object?

== Copying Data Into Running Container Filesystems

The trick to this is to use the `sudo docker cp <files> CONTAINER_ID:/<destination_dir>

To extract files from a container, such as after a batch run:`sudo docker cp CONTAINER_ID:/<source_dir> /<local_dir>`

Let's try this with our running container from above.

Let's run the container again as it was built:

[source,bash]
$ sudo docker run -d --name python-container -p 8080:8080  docker-list-files

NOTE: The --name parameter has to be passed right after the -d parameter

For the first time today, we are naming the running container. Without the `--name` parameter, you may have noticed that two-word random names have been generated. Let's step back from the hexadecimal and random, and call this instance "python-container"

[source,bash]
---
$ touch exoskeleton{1,2,3,4}.txt
$ for i in {1..4} ; do sudo docker cp ./exoskeleton$i.txt python-container:/datafiles ; done
$ curl localhost:8080/data_files

tip: The docker cp command does not like wildcard globbing, so use a for loop to copy in the data.

results in:

```
[student@podman ~]$ curl localhost:8080/data_files
["data1.csv", "data1.txt", "data10.csv", "data10.txt", "data11.csv", "data11.txt", "data12.csv", "data12.txt", "data13.csv", "data13.txt", "data14.csv", "data14.txt", "data15.csv", "data15.txt", "data16.csv", "data16.txt", "data17.csv", "data17.txt", "data18.csv", "data18.txt", "data19.csv", "data19.txt", "data2.csv", "data2.txt", "data20.csv", "data20.txt", "data21.csv", "data22.csv", "data23.csv", "data24.csv", "data25.csv", "data26.csv", "data27.csv", "data28.csv", "data29.csv", "data3.csv", "data3.txt", "data30.csv", "data4.csv", "data4.txt", "data5.csv", "data5.txt", "data6.csv", "data6.txt", "data7.csv", "data7.txt", "data8.csv", "data8.txt", "data9.csv", "data9.txt", "exoskeleton[1,2,3,4}.txt", "exoskeleton1.txt", "exoskeleton2.txt", "exoskeleton3.txt", "exoskeleton4.txt"]
```
We can see we were able to move the data files to the container.

Let's see if we can get all of the datfiles out

[source,bash]
$ mkdir output
$ sudo docker cp python-container:/datafiles ./output/
$ ls -R ./output

yields:
```
./output:
datafiles

./output/datafiles:
data10.csv  data13.txt  data17.csv  data1.txt   data25.csv  data30.csv  data6.csv  data9.txt
data10.txt  data14.csv  data17.txt  data20.csv  data26.csv  data3.csv   data6.txt  exoskeleton[1,2,3,4}.txt
data11.csv  data14.txt  data18.csv  data20.txt  data27.csv  data3.txt   data7.csv  exoskeleton1.txt
data11.txt  data15.csv  data18.txt  data21.csv  data28.csv  data4.csv   data7.txt  exoskeleton2.txt
data12.csv  data15.txt  data19.csv  data22.csv  data29.csv  data4.txt   data8.csv  exoskeleton3.txt
data12.txt  data16.csv  data19.txt  data23.csv  data2.csv   data5.csv   data8.txt  exoskeleton4.txt
data13.csv  data16.txt  data1.csv   data24.csv  data2.txt   data5.txt   data9.csv
[student@podman ~]$ 
```
NOTE: While we cannot use wildcard file globbing for copying, we can copy directories.


link:../containers.adoc[Return to workshop top page]






link:../containers.adoc[Return to workshop top page]