:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamationpodman build -f Dockerfile.ubi -t hello-ubi-py_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= TODO catch basin for the Workshop

podman inspect a pos

TIP: Should we want to temporarily disconnect from this running container, and come back, (regardless of the --rm flag), do this. From the container connection, issue a ctrl-p ctrl-q. To come back, issue the `docker attach <container-name>` command. Hit `<enter>` if you do not immediately see the connection.

podman run -it --rm ubi8/python-38 /opt/app-root/bin/python

Show how to work containers / docker registry search controls

Clean this up https://access.redhat.com/documentation/en-us/red_hat_software_collections/3/html/using_red_hat_software_collections_container_images/sti

https://computingforgeeks.com/install-source-to-image-toolkit-on-linux/
playbook to register the vms to me
to install the packages
and to install the two auth.json files


[source,bash]
sudo vim /etc/containers/registries.conf

sudo podman build . -f Containerfile.support-tools -t support-tools

sudo podman run -it --rm support-tools

data container (exposes volumes)

sudo podman login registry.access.redhat.com

-dt for background runs

sudo podman run -dt --name data-container -v $PWD/data/data:/mnt/data -v $PWD/data/keys:/mnt/keys data-container

sudo podman container runlabel run --display perfect-tool

ctrl-p ctrl-q exit and not end container

podman run --volumes-from 

sudo podman attach <container-name>

prune command -- check out system  subcommand   rmi --all 

podman pod create -n new-pod

sudo podman ps -p --all shows the paused container. 

pause container is a "keep-alive" and a redirector to the right 

sudo podman run --pod=new:tools-pod -dt 

coloring books / e books

# install the packages needed.
sudo yum install podman buildah skopeo slirp4netns  -y

Dockerfile Parameters:
WORKDIR

COPY src/ . # copies source to workdir 

CMD ["python", "./server.py" ]

cacheing efficiency. When a change in a layer is detected, that layer and all the ones coming after are being rebuilt.

For debugger / reloader:
in server.run(debug=True,host='0.0.0.0, # Data Containers
# FROM ubi-minimal
FROM fedora-minimal
VOLUME [ “/mnt/data” ]
VOLUME [ “/mnt/keys” ]
[source,bash]
--
# first stage
FROM python:3.8 AS builder
COPY requirements.txt .
# install dependencies to the local user directory (eg. /root/.local)
RUN pip install --user -r requirements.txt
# second unnamed stage
FROM python:3.8-slim
WORKDIR /code
# copy only the dependencies installation from the 1st stage image
COPY --from=builder /root/.local/bin /root/.local
COPY ./src .
# update PATH environment variable
ENV PATH=/root/.local:$PATH
CMD [ "python", "./server.py" ]
--

Set up docker loggingOn 

link:../containers.adoc[Return to workshop top page]

