:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= TODO for the Workshop


= Containers Basics

Containers run on the Linux operating system[1]. 


There are "Docker Containers" for Window Container Basics, but the majority of containers for Kubernetes run on Linux clustered hosts. These hosts are run on AWS (Amazon Web Services), so hopefully your firewall will not block that.

We will work within a RHEL (Red Hat Enterprise Linux) instance in order to orient ourselves with, and develop container images.


=== Docker and Podman Commands - an Introduction



[source,bash]
sudo docker run hello-world

```Hello from Docker!
This message shows that your installation appears to be working correctly.
```


== Containers on a Red Hat Server
Containers running on a Red Hat server will be our initial use case for today. We will be using Red Hat Enterprise Linux, and build the containers on this platform, and run them on the platform as well.

Red hat provides some Builder images that are terrific for ease of use both in the build and deployment scenarios.



link:../containers.adoc[Return to workshop top page]




